# Tag List: https://mcr.microsoft.com/v2/devcontainers/ruby/tags/list
FROM mcr.microsoft.com/devcontainers/ruby:1-3.2-bullseye

# Install required packages for Jekyll
RUN gem install bundler jekyll

# Expose the port for Jekyll's built-in server
EXPOSE 4000
